"""Training table update

Revision ID: 2fb7edac0158
Revises: 441a1ba46e4d
Create Date: 2024-01-12 03:25:53.090309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb7edac0158'
down_revision: Union[str, None] = '441a1ba46e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('is_finished', sa.Boolean(), nullable=False))
    op.add_column('training', sa.Column('finishing_time', sa.DateTime(), nullable=True))
    op.add_column('training', sa.Column('span', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training', 'span')
    op.drop_column('training', 'finishing_time')
    op.drop_column('training', 'is_finished')
    # ### end Alembic commands ###
