"""Added birthdate to the users table

Revision ID: 6d99824a2847
Revises: ab393e11c556
Create Date: 2023-12-23 15:00:18.826793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d99824a2847'
down_revision: Union[str, None] = 'ab393e11c556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthdate', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birthdate')
    # ### end Alembic commands ###
