"""Metric table name column added

Revision ID: 71409b1b594d
Revises: 97803a0fbd45
Create Date: 2024-01-04 23:18:47.015129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71409b1b594d'
down_revision: Union[str, None] = '97803a0fbd45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'metric', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metric', type_='unique')
    op.drop_column('metric', 'name')
    # ### end Alembic commands ###
