"""User talbe fix

Revision ID: d94491745e78
Revises: e718767f3654
Create Date: 2024-01-06 23:23:05.796183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94491745e78'
down_revision: Union[str, None] = 'e718767f3654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'calories',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'proteins',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'fats',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'carbohydrates',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'water',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'water',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'carbohydrates',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'fats',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'proteins',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'calories',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
