"""Diet models creation

Revision ID: e718767f3654
Revises: 71409b1b594d
Create Date: 2024-01-06 23:14:10.491126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e718767f3654'
down_revision: Union[str, None] = '71409b1b594d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('proteins', sa.Integer(), nullable=False),
    sa.Column('fats', sa.Integer(), nullable=False),
    sa.Column('carbohydrates', sa.Integer(), nullable=False),
    sa.Column('water', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish_in_meal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dish_id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('proteins', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('fats', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('carbohydrates', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('water', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'water')
    op.drop_column('user', 'carbohydrates')
    op.drop_column('user', 'fats')
    op.drop_column('user', 'proteins')
    op.drop_column('user', 'calories')
    op.drop_table('dish_in_meal')
    op.drop_table('meal')
    op.drop_table('dish')
    # ### end Alembic commands ###
