"""Dish model fix

Revision ID: e885341e9101
Revises: d94491745e78
Create Date: 2024-01-06 23:26:21.114507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e885341e9101'
down_revision: Union[str, None] = 'd94491745e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'dish', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.drop_column('dish', 'owner_id')
    # ### end Alembic commands ###
