"""ExerciseInTraining created_at added

Revision ID: f1f282da2bb6
Revises: 2fb7edac0158
Create Date: 2024-01-13 05:17:36.853814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f282da2bb6'
down_revision: Union[str, None] = '2fb7edac0158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_in_training', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_in_training', 'created_at')
    # ### end Alembic commands ###
