"""Added trainer-relationship table

Revision ID: f8ba424b6a37
Revises: 68e8572bf525
Create Date: 2023-12-31 15:18:41.080402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ba424b6a37'
down_revision: Union[str, None] = '68e8572bf525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer',
    sa.Column('trainer_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trainer_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainer')
    # ### end Alembic commands ###
